### ISSUE TITLE
Some Errors

### ISSUE THREAD

**Issue by pmjklemm** [bougui505/alignscape#1]
Hi there, 

I have 3 problems:

(1) I have some errors with `python3 -m som_seq --test`:

```
$ python3 -m som_seq --test

**********************************************************************
File "/home/paul/test_SOMSeq/quicksom_seq/som_seq.py", line 173, in __main__.iscore_matrix_vec
Failed example:
    scores = iscore_matrix_vec(vec1, b62=b62, verbose=True)
Exception raised:
    Traceback (most recent call last):
      File "/home/paul/miniconda3/envs/WE/lib/python3.11/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest __main__.iscore_matrix_vec[4]>", line 1, in <module>
        scores = iscore_matrix_vec(vec1, b62=b62, verbose=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/paul/test_SOMSeq/quicksom_seq/som_seq.py", line 189, in iscore_matrix_vec
        matv2 = torch.matmul(matrix[None, ...], torch.swapaxes(vec1[..., :-2], 1, 2))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_bmm)
**********************************************************************
1 items had failures:
   2 of   6 in __main__.iscore_matrix_vec
***Test Failed*** 2 failures.
``` 

(2) and the test_som fails with out of memory, any idea how I can improve this for my nvidia Quadro P620? Or is there a way to disable GPU and use the package on CPU alone?

```
$ ./test_som.sh

(...)

/tmp/zshsfGzTa opened with object id 140309483654656 for worker 16
/tmp/zshsfGzTa opened with object id 140309483654480 for worker 15
/tmp/zshsfGzTa opened with object id 140309483655184 for worker 19
/home/paul/miniconda3/envs/WE/lib/python3.11/site-packages/torch/_functorch/deprecated.py:58: UserWarning: We've integrated functorch into PyTorch. As the final step of the integration, functorch.vmap is deprecated as of PyTorch 2.0 and will be deleted in a future version of PyTorch >= 2.3. Please use torch.vmap instead; see the PyTorch 2.0 release notes and/or the torch.func migration guide for more details https://pytorch.org/docs/master/func.migrating.html
  warn_deprecated('vmap', 'torch.vmap')
1/1: 0/30 | alpha: 0.500000 | sigma: 25.000000 | error: 643.780945 | time: 0:00:00.562173 | eta: 0:00:01.124346
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/paul/test_SOMSeq/quicksom_seq/som_seq.py", line 384, in <module>
    main(ali=args.aln,
  File "/home/paul/test_SOMSeq/quicksom_seq/som_seq.py", line 315, in main
    somobj.fit(dataset=dataloader,
  File "/home/paul/test_SOMSeq/quicksom_seq/quicksom_seq/quicksom/som.py", line 402, in fit
    bmu_loc, error = self.__call__(batch, learning_rate_op=lr_step)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/paul/test_SOMSeq/quicksom_seq/quicksom_seq/quicksom/som.py", line 317, in __call__
    delta = torch.mul(learning_rate_multiplier.reshape(*learning_rate_multiplier.size(), 1).expand_as(delta), delta)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 484.00 MiB (GPU 0; 1.95 GiB total capacity; 565.17 MiB already allocated; 401.94 MiB free; 1014.00 MiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

(3) the colab notebook fails in section `4. Compute the Self Organizing Map` for the test data (human_kinome_noPLK5): 

``` 
n_input: 496
opening /content/quicksom_seq/data/Human_kinome/human_kinome_noPLK5.aln

---------------------------------------------------------------------------

XlaRuntimeError                           Traceback (most recent call last)

[<ipython-input-11-ed54f830ffaa>](https://localhost:8080/#) in <cell line: 10>()
     13                scheduler="exp", alpha=alpha, sigma= sigma)
     14 else:
---> 15   som_seq.main(ali=test_aln, batch_size=10, use_jax=True,
     16                outname="som", somside=somside, nepochs=nepochs,
     17                scheduler="exp", alpha=alpha, sigma= sigma)

20 frames

[/usr/local/lib/python3.10/dist-packages/jax/_src/compiler.py](https://localhost:8080/#) in backend_compile(backend, module, options, host_callbacks)
    249   # TODO(sharadmv): remove this fallback when all backends allow `compile`
    250   # to take in `host_callbacks`
--> 251   return backend.compile(built_c, compile_options=options)
    252 
    253 

XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
```

**Comment by IFilella** [comment]
Hi and thanks for your feedback!

> (1) I have some errors with `python3 -m som_seq --test`:

The '--test' flag was a remnant of an older testing process. It has been deprecated from the current versions.

> (2) and the test_som fails with out of memory, any idea how I can improve this for my nvidia Quadro P620? Or is there a way to disable GPU and use the package on CPU alone?

The 'test_som' now runs with a default batch size of 5, previously set at 10. Loading the model and batches for 'test_som' currently requires 1197 MB, ensuring compatibility with your GPU. To further reduce GPU memory allocation, users can decrease the batch size, the SOM size, or trim the MSA to retain only informative sites.

> (3) the colab notebook fails in section `4. Compute the Self Organizing Map` for the test data (human_kinome_noPLK5):

Solved. The issue stemmed from Jax versions. Collab now runs the PyTorch version of AlignScape by default.
